### ISSUE TITLE
Run autograding on R notebook?

### ISSUE THREAD

**Issue by matthew-brett** [ucbds-infra/ottr#5]
Sorry if this is the wrong place to ask - but is there an example somewhere to show how to run autograding on an R notebook?  I mean the equivalent of:

```
otter run hw00.ipynb
```

[from this page](https://otter-grader.readthedocs.io/en/latest/workflow/executing_submissions/otter_run.html) but for an R Rmd notebook:

```
otter run hw00.Rmd
```

?  @LJCompton and I are trying to get this working for a bioinformatics course.

**Comment by chrispyles** [comment]
HI @matthew-brett -- sorry for the (extremely) delayed reply. (We usually handle issues for ottr in the repo for [otter-grader](https://github.com/ucbds-infra/otter-grader).) This functionality exists currently exactly as you describe it:

```console
otter run hw00.Rmd
```

will run Otter on an Rmd file, provided that your autograder zip file is configured to work with R (i.e. it should have `"lang": "r"` in its `otter_config.json` file).
